#!/usr/bin/python3
#
# Verilog $readmemh() file output
#
# 07-23-2015 E. Brombaugh

import numpy as np

def write_memh(fname, data):
    # open output file and add header
    fh = open(fname, "w", encoding="utf-8")
    fh.write("// memory init data\n")
    fh.write("// Auto-generated by write_memh.py\n")

    # dump data as hex
    for value in data:
        value = value&0xffff
        fh.write("{0:0=4x}\n".format(value))

    fh.close()

    
